---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: banned-api
  name: banned-api
  entry: banned-api-hook
  description: Formats C, C++, Objective-C, and Java code
  types_or: [c, c++, c#, objective-c, java]
  language: python
- id: get-new-hooks
  name: get-new-hooks
  entry: get-new-hooks
  description: Smmm
  # files: [.pre-commit-config.yaml]
  language: python
